# Generated by Django 4.1.5 on 2023-05-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_carslocation_guid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(max_length=255)),
            ],
        ),
    ]
