# Generated by Django 4.1.5 on 2023-05-21 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_incidents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidents',
            old_name='langitude',
            new_name='latitude',
        ),
    ]
